export const sample_foods = [
  {
    id: "1",
    name: "Margherita Pizza",
    cookTime: "20-30",
    price: 149,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Club Sandwich",
    price: 49,
    cookTime: "10-20",
    favorite: true,
    origins: ["US"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["Lunch", "Sandwich"],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 4.5,
    cookTime: "15-25",
    favorite: false,
    origins: ["germany", "US"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "French Fries",
    price: 79,
    cookTime: "15-25",
    favorite: true,
    origins: ["belgium", "france"],
    stars: 5,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Fries"],
  },
  {
    id: "5",
    name: "Sushi",
    price: 599,
    cookTime: "40-50",
    favorite: false,
    origins: ["japan"],
    stars: 4.5,
    imageUrl: "food-5.jpg",
    tags: ["Sushi"],
  },
  {
    id: "6",
    name: "Vegetarian Pizza",
    price: 99,
    cookTime: "20-30",
    favorite: false,
    origins: ["italy", "asia"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },

  {
    id: "7",
    name: "Veg Biryani",
    price: 99,
    cookTime: "20-30",
    favorite: true,
    origins: ["india"],
    stars: 5,
    imageUrl: "/foods/food-7.jpg",
    tags: ["Lunch", "Biryani"],
  },

  {
    id: "8",
    name: "Samosa",
    price: 19,
    cookTime: "10-20",
    favorite: true,
    origins: ["india"],
    stars: 4.5,
    imageUrl: "/foods/food-8.jpg",
    tags: ["FastFood", "Samosa"],
  },

  {
    id: "9",
    name: "Chicken Skewers",
    price: 199,
    cookTime: "20-30",
    favorite: false,
    origins: ["south asia", "middle east"],
    stars: 4.5,
    imageUrl: "/foods/food-9.jpg",
    tags: ["Lunch", "Chicken Skewers"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "TastyCraft",
    email: "tastycraft@gmail.com",
    password: "12345",
    address: "Shivaji Road, Pune, Maharashtra",
    isAdmin: false,
  },
];
